[workspace]
resolver = "2"
members = [
    "rbtcore",
    "rbtcli",
    "ansx",
    "flownet",
]

[workspace.package]
edition = "2021"
version = "0.0.1"



[workspace.dependencies]
flownet = { path = "./flownet" } 