[package]
name = "rbtcore"
version = "0.0.1"
edition = "2024"
license = "MIT"

[lib]
path = "src/lib.rs"

[features]
# Feature flags for individual modules
alpha = []
beta = []
gamma = []

default = ["alpha"] 